import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/lib/Provider/themeProvider";
import ReactQueryProvider from "@/react-query";
import { ReduxProvider } from "@/redux/Provider";
import { Toaster } from "sonner";
const manrope = Manrope({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope}`}>
          <ReduxProvider>
            <Provider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <ReactQueryProvider>
                {children}
                <Toaster />
              </ReactQueryProvider>
            </Provider>
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
